meta_product_name: "SkillsUpp"
meta_title: "SkillsUpp - Skills for life"
meta_description: "Work Play Learn - Learn New SkiLls and have fun while learning."
meta_image: "cover.png" # should exist in `app/assets/images/`
