meta_product_name: "SkillsUpp"
meta_title: "SkillsUpp - Skills for life"
meta_description: "Keep the skills you acquired during courses, conferences or the like."
meta_image: "cover.png" # should exist in `app/assets/images/`
